# FIX: Results not properly updating
# ! UPDATE ACCORDING TO YOUR LLVM PATH

BUILD_PATH=${LLVM_BIN_PATH}
LLVM_CONFIG=$(BUILD_PATH)/llvm-config
CXX=$(BUILD_PATH)/clang++ -std=c++17 -O1
# CXX=$(BUILD_PATH)/clang++ -std=c++17 -O0
# removed -g flag, add if needed
CXXFLAGS= `$(LLVM_CONFIG) --cppflags` -fPIC -fno-rtti -fsanitize=address
# CXXFLAGS= `$(LLVM_CONFIG) --cppflags` -fPIC -fno-rtti -Xclang -disable-O0-optnone
LDFLAGS=`$(LLVM_CONFIG) --ldflags` -Wl,-znodelete

ifndef VERBOSE
.SILENT:
endif

.PHONY: test 

all: build test cfg_before cfg_after

build: HPSSA_new.cpp headers/HPSSA_new.h TDestruction.cpp headers/TDestruction.h
	$(CXX) -v
	@mkdir -p build
	$(CXX) -c HPSSA_new.cpp -o build/HPSSA_new.cpp.o $(CXXFLAGS)
	$(CXX) $(CXXFLAGS) -shared build/HPSSA_new.cpp.o -o build/HPSSA_new.cpp.so $(LDFLAGS)
#	$(CXX) -c TDestruction.cpp -o build/TDestruction.cpp.o $(CXXFLAGS)
#	$(CXX) $(CXXFLAGS) -shared build/TDestruction.cpp.o -o build/TDestruction.cpp.so $(LDFLAGS)

test: build tests/test.cpp BBProfiler/profileInfo.txt 
	# use the same test case which was profiled 
	rm tests/test.cpp
	cp BBProfiler/tests/test.cpp tests/test.cpp
	$(CXX) -c -emit-llvm $(CXXFLAGS) tests/test.cpp -o IR/BC/test.bc
	$(CXX) -S -emit-llvm $(CXXFLAGS) tests/test.cpp -o IR/LL/test.ll
	$(BUILD_PATH)/opt -instnamer -mem2reg IR/BC/test.bc -S -o IR/LL/test_mem2reg.ll
	$(BUILD_PATH)/opt -load-pass-plugin=build/HPSSA_new.cpp.so -passes=hpssa_new -S -f -time-passes IR/LL/test_mem2reg.ll -o IR/LL/test_HPSSA_new.ll 2> output/custom_HPSSA_new.log
	# $(BUILD_PATH)/opt -load-pass-plugin=build/TConditional.cpp.so -passes=tcond -time-passes IR/LL/test_hpssa.ll -S -o IR/LL/test_tcond.ll -f 2> output/custom_tcond.log
	# $(BUILD_PATH)/opt -load-pass-plugin=build/TDestruction.cpp.so -passes=tdstr -time-passes IR/LL/test_HPSSA_new.ll -S -o IR/LL/test_tdstr.ll -f 2> output/custom_tdstr.log
	# Handle exit code of diff(1 if changes found).
	diff IR/LL/test_mem2reg.ll IR/LL/test_HPSSA_new.ll > output/changes_HPSSA_new.log; [ $$? -eq 1 ]
	# diff IR/LL/test_HPSSA_new.ll IR/LL/test_tdstr.ll > output/changes_tdstr.log; [ $$? -eq 1 ]


cfg_before: build tests/test.cpp BBProfiler/profileInfo.txt 
	$(BUILD_PATH)/opt --dot-cfg IR/LL/test_mem2reg.ll -o IR/BC/test_mem2reg.bc 
	make dot2png
	mv ./IR/cfg/.main.dot.png ./IR/cfg/cfg_before.png

dom_before:build tests/test.cpp BBProfiler/profileInfo.txt 
	$(BUILD_PATH)/opt --dot-cfg IR/LL/test_mem2reg.ll -o IR/BC/test_mem2reg.bc 
	make dot2png
	mv ./IR/cfg/.main.dot.png ./IR/cfg/dom_before.png

cfg_after: test 
	$(BUILD_PATH)/opt --dot-cfg IR/LL/test_HPSSA_new.ll -o IR/BC/test_HPSSA_new.bc
	# $(BUILD_PATH)/opt --dot-cfg IR/LL/test_tcond.ll -o IR/BC/test_tcond.bc 
	make dot2png
	mv ./IR/cfg/.main.dot.png ./IR/cfg/cfg_after.png

dom_after: test
	$(BUILD_PATH)/opt --dot-dom-only IR/LL/test_HPSSA_new.ll -o IR/BC/test_HPSSA_new.bc 
	make dot2png
	mv ./IR/cfg/.main.dot.png ./IR/cfg/dom_after.png

dot2png: 
	mv .*.dot IR/cfg/
	find IR/cfg/ -name *.dot | xargs -I name dot -Tpng name -o name.png

clean: 
	rm -rf output && mkdir output 
	rm -rf IR && mkdir IR && mkdir IR/BC && mkdir IR/LL && mkdir IR/cfg 
	rm -f *.s *.out *.log *.txt